### ISSUE TITLE
When inserting value with "?" then ":pdooci_m" is inserted instead of "?"

### ISSUE THREAD

**Issue by CZechBoY** [taq/pdooci#12]
Hi,
here is quick example:
`
$db->query("INSERT INTO table (col) VALUES ('abc?')");
`
and it generates query "INSERT INTO table (col) VALUES ('abc:pdooci_m0')".

Check the Statement::insertMarks($query) function.

**Comment by taq** [comment]
Good question. I'd like to use the prepared statement form, but using strings this way should work too. What is happening is that the question marks are searched to be replaced to the prepared statement variables. Wondering here how can we deal with this. Maybe don't replace the question mark if it is inside single quotes.

**Comment by CZechBoY** [comment]
Yes, in the strings you should ommit questionmarks.

But you can have sql query like
```
INSERT INTO table (col) VALUES (' \'abcdef\' ?');
```

**Comment by taq** [comment]
But on both cases the question mark is contained between the single quotes. :-)

**Comment by CZechBoY** [comment]
Yep, my bad :-))

**Comment by taq** [comment]
I just found the regular expression to check for it:

```php
$query = "insert into bla values ('?abc', ?, ?, 'xyz?')";
$regex = '/(?<!\')\?(?!\')/';
preg_match_all($regex, $query, $marks);
var_dump($marks);
array(1) {
  [0]=>
  array(2) {
    [0]=>
    string(1) "?"
    [1]=>
    string(1) "?"
  }
}
```
Just the two question marks not contained in quotes are there. Just need a way to find a way to replace them on the query string. On JavaScript we have an option to send the position of the match, but I could not find a way to do this on PHP. Seems we can find the same behaviour with PHP with:

```php
$pos = -1;
echo preg_replace_callback($regex, function($matches) use (&$pos) { $pos++; return ":pdooci_m$pos"; }, $query);
// => insert into bla values ('?abc', :pdooci_m0, :pdooci_m1, 'xyz?')
```

This can replace the `insertMarks` contents.

**Comment by taq** [comment]
Just made a new commit, check it out. To your first examples, it worked ok.

**Comment by CZechBoY** [comment]
Everything works at me :-))
Thanks!

**Comment by taq** [comment]
Cool! :-)
