### ISSUE TITLE
Bind array for sql IN(?)

### ISSUE THREAD

**Issue by CZechBoY** [taq/pdooci#14]
Hi,
do you know how to bind parameter with type array?
I want sth like this:
`
$sql = 'SELECT * FROM blah WHERE id IN (?)';
$ids = [1,2,3,4,5];
$pdo->query($sql)->execute($ids);
`

Thanks.

**Comment by taq** [comment]
Hi! Take a look on "Example #5 Execute a prepared statement using array for IN clause" at http://php.net/manual/en/pdostatement.execute.php

**Comment by CZechBoY** [comment]
Ok, I use this already :-)
