### ISSUE TITLE
Class 'PDOStatement' not found

### ISSUE THREAD

**Issue by paragshar** [taq/pdooci#17]
I get this issue when using this library.

Class 'PDOStatement' not found in /vagrant/vendor/taq/pdooci/src/Statement.php

In this class 

class Statement extends \PDOStatement implements \IteratorAggregate

you seem to be including PDOStatement from root scope. But in my installation this is not available, as I do not have any PDO module installed.

**Comment by taq** [comment]
Hey! But you need to have installed PHP PDO to use it. Don't your PHP version has PDO already installed? It is enabled by default since PHP 5.1.0. http://php.net/manual/en/pdo.installation.php

**Comment by taq** [comment]
11 days, no answer, closing ...
