### ISSUE TITLE
Statement->execute() needs to bind values by reference

### ISSUE THREAD

**Issue by renatofdds** [taq/pdooci#18]
Currently, execute() on PDOOCI\Statement#157 uses bindValue(), which prototype's accepts a copy for the value instead of the reference. 

This needs to be changed to bindParam which accepts the reference because oci_bind_by_name needs the reference to the variable (as in https://secure.php.net/manual/en/function.oci-bind-by-name.php), otherwise the execute() silently fails with multiple parameters.

Tested on PHP 7.0.9, OCI 2.1.1, Oracle Instant Client 12.1, Oracle Library Version 12.1.0.2.0.

**Comment by taq** [comment]
Hey, thanks, I'll take a look on this tomorrow.

**Comment by taq** [comment]
Done, take a look.

**Comment by renatofdds** [comment]
That is exactly what i did, works for me. Thank you!
