### ISSUE TITLE
Why my code isn't easily translated

### ISSUE THREAD

**Issue by goldsnake90** [taq/pdooci#22]
I have some issues to make it work.

I have two identical tables, one in MySQL and the other in Oracle. However it seems that only my pdo code to call from the table in MySQL works.
It seems that I am connected with my oracle database, so I don't think that the problem is there.

This is the method i use to get my data from MySQL:

        public function TestMySQL() {
                $db = dbConn::getConnection();

                $query =   'SELECT NAME FROM TESTTABLE';
                $statement = $db->prepare($query); 
                $statement->execute();
                $object = $statement->fetchAll(PDO::FETCH_OBJ);
                return $object;
    }

And the class to connect into the database:

        class dbConn {

            //variabili per tenere un oggetto di connessiane
            protected static $db;
            private $uname;
            private $passwd;
            private $hostname;
            private $dbname;

            //costruttore privato - non può essere inizializzato esternamente
            private function __construct() {
               $this->uname = "xxx";
                $this->passwd = "xxx";
                $this->hostname = "xxx";
                $this->dbname = "xxx";

                try {
                    // assegna un oggetto PDO alla variabile di db
                    self::$db = new PDO('mysql:charset=utf8mb4;host=' . $this->hostname . ';dbname=' . $this->dbname, $this->uname, $this->passwd);
                    self::$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                } catch (PDOException $e) {

                    $e->getMessage();
                }
            }

        // funzione di get per la connessione. Metodo statico.
            public static function getConnection() {

        //Garantisce una singola istanza, se non esiste alcun oggetto di connessione allore ne crea uno.
                if (!self::$db) {
                    new dbConn();
                }
        //ritorna la connessione
                return self::$db;
            }
        }

And this is from Oracle:

            public function TestOracle() {
                $db = Dboracle::getConnectionOra();

                $query =   'SELECT NAME FROM TESTTABLE';
                $statement = $db->prepare($query); 
                $statement->execute();
                $object = $statement->fetchAll(PDO::FETCH_OBJ);
                return $object;
            }

And the class to connect into the database:

        require_once "PDOOCI/PDO.php";

        class Dboracle {

            //variabili per tenere un oggetto di connessiane
            protected static $db;
            private $uname;
            private $passwd;
            private $hostname;
            private $servicename;
            private $dbname;

            //costruttore privato - non può essere inizializzato esternamente
            public function __construct() {
                $this->uname = "xxx";
                $this->passwd = "xxx";
                $this->hostname = "xxx";
                $this->servicename = "xxx";
                $this->dbname = "xxx";

                try {
                    // assegna un oggetto PDO alla variabile di db
                    $tns = "(DESCRIPTION=(ADDRESS_LIST = "
                            . "(ADDRESS = (PROTOCOL = TCP)(HOST = " . $this->hostname . ")"
                            . "(PORT = 1521)))(CONNECT_DATA=(SERVICE_NAME=" . $this->servicename . ")))";
                    $connStr = "oci:dbname=" . $tns;
                    self::$db = new PDOOCI\PDO($connStr, $this->uname, $this->passwd);
                    self::$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
 
                } catch (PDOException $e) {

                    echo $e->getMessage();
                }
            }

        // funzione di get per la connessione. Metodo statico.
            public static function getConnectionOra() {

        //Garantisce una singola istanza, se non esiste alcun oggetto di connessione allore ne crea uno.
                if (!self::$db) {

                    new Dboracle();
                }

        //ritorna la connessione
                return self::$db;
            }
        }
I am trying to call the table in my index.php in this way:
            <?php
            
            $test = new Class();
                        
            $testlist = $test->TestOracle(); /* Or $test->TestMySQL(); */
                         
                foreach ($testlist as $element) {
                    echo '<a href="#" class="servicelink">' . $element->NAME . '</a>';
                }
      
            ?>
The error I am getting with "TestOracle" is:
     Warning: Invalid argument supplied for foreach() in "place where my foreach is called.
I want to thank you for your precious help

**Comment by taq** [comment]
Do you have a valid connection on:

```
self::$db = new PDOOCI\PDO($connStr, $this->uname, $this->passwd);
```

On the `getConnectionOra` method? If so, can you use the `var_dump` method to check what is the contents of the `$object` var returned on

```
$object = $statement->fetchAll(PDO::FETCH_OBJ);
```
