### ISSUE TITLE
PHP 5.6 or PHP 7.1 Support?

### ISSUE THREAD

**Issue by thomaswiedmann** [taq/pdooci#25]
The comment block shows
```

/**
 * PDOCI
 *
 * PHP version 5.3
```

Is this the max. tested PHP Version?
Thanks

**Comment by taq** [comment]
No, I'm using it with newer versions. That is the min version you need to use it.

**Comment by thomaswiedmann** [comment]
Perfekt! So I can start a small test with PHP 5.6 on Window Plattform using ORACLE 12.

Thanks!

**Comment by taq** [comment]
You're welcome.
