### ISSUE TITLE
Enable dbms_output

### ISSUE THREAD

**Issue by bren1818** [taq/pdooci#27]
Hi there, first and foremost, thank you for this project. It's fantastic!

I was wondering if there is a way to capture the DMBS output. I have a few statements which ouput data using the dbms_output.putline, which I need to capture. 

Is there a flag which I can enable to allow/capture dbms_ouput? I tried adding this to the beginning of the statement:  DBMS_OUTPUT.ENABLE(NULL); and this to the end: dbms_output.put_line( lv_msg_out || '| ' || lv_update_out || '| ' || lv_sqlerrm_out); where those variables should be populated.

Thanks kindly!

---EDIT--- Please disregard, I found I could bind the parameters to a PHP variable using the "PARAM_INPUT_OUTPUT"

	$fetch->bindParam(':lv_msg_out', 	$lv_msg_out,  		PDO::PARAM_STR|PDO::PARAM_INPUT_OUTPUT, 4000);
		$fetch->bindParam(':lv_update_out', $lv_update_out, 	PDO::PARAM_STR|PDO::PARAM_INPUT_OUTPUT, 1);
		$fetch->bindParam(':lv_sqlerrm_out', $lv_sqlerrm_out,  	PDO::PARAM_STR|PDO::PARAM_INPUT_OUTPUT, 4000);

**Comment by taq** [comment]
Hey, you're welcome. :-)
