### ISSUE TITLE
Statement->execute() doesn't like bind variables with null values

### ISSUE THREAD

**Issue by cobhimself** [taq/pdooci#29]
We started using your library and it seems to be working well most of the time. However, if we ever have a bind variable we want to fill with a null value, we get "Cannot insert NULL into ..." or other errors referencing empty bind values. Null is a valid value for some of our bind params (for example, when inserting into a table which has a trigger that will fill in a primary key). Do you have any insight as to what we should do in these cases if we are to use your library?

**Comment by taq** [comment]
Hey! I don't have PHP projects anymore, and not an Oracle database to test it, so I can't give you a real valid position about this. I agree that nulls are valid values, it should be working ...
