### ISSUE TITLE
 Undefined variable: case in file: vendor/taq/pdooci/src/Statement.php on line: 642

### ISSUE THREAD

**Issue by kaiduerkop** [taq/pdooci#32]
`return array_map(
            function ($item) { 
                if (is_array($item)) {
                    $item = array_change_key_case($item, $case);
                }
                return $item;
            }, array_change_key_case($result, $case)
        );`

Replace 
function ($item)

with 
function ($item) use ($case) {

**Comment by taq** [comment]
It's already there: https://github.com/taq/pdooci/blob/master/src/Statement.php

What version are you using?

**Comment by taq** [comment]
Btw, is there since 2 years ago.

**Comment by kaiduerkop** [comment]
The version from which will be provided by composer

"taq/pdooci": "^1.0",

composer installs version 1.0.7
- Installing taq/pdooci (1.0.7): Loading from cache

**Comment by taq** [comment]
Ouch! I didn't updated the version number and it's stuck on Composer since 2 years ago. Thanks for warning me!
I'll release a new version right now.

**Comment by taq** [comment]
Please check it out.

**Comment by kaiduerkop** [comment]
Yes, it pushs now v1.0.8.
Thanks :)
