### ISSUE TITLE
\PDO::FETCH_BOTH is only fetched as \OCI_NUM

### ISSUE THREAD

**Issue by CZechBoY** [taq/pdooci#7]
In method `Statement::fetchAll `
line `\oci_fetch_all($this->_stmt, $rst, 0, -1, \OCI_FETCHSTATEMENT_BY_ROW + \OCI_NUM + \OCI_ASSOC);` is wrong, but I have no idea how to fix it.
Using FETCH_ASSOC temporarily :)

**Comment by taq** [comment]
Yeah, seems we can't use FETCH_BOTH. :-( I remember I got a link for this but I'm not finding it right now.

**Comment by taq** [comment]
http://php.net/manual/pt_BR/function.oci-fetch-all.php#114664

**Comment by taq** [comment]
Uhn, can we close this now? I didn't find the reference, but seems to be a problem with the OCI layer, not PDOOCI.

**Comment by CZechBoY** [comment]
Isn't here any workaround? Sth like fetch NUM and append ASSOC?

**Comment by taq** [comment]
Please try first using pure OCI functions (calling directly `oci_fetch_all`, not using PDO) to check if it works on some way. As I recall, there were some problems right there.

**Comment by ruivoh** [comment]
I "solved" it by duplicating the _stmt, the oci_execute, and by changing the Statement::fetchAll() function, in the case part, like this:

            case \PDO::FETCH_BOTH:	
                \oci_fetch_all($this->_stmt, $rst, 0, -1, \OCI_FETCHSTATEMENT_BY_ROW + \OCI_NUM);				
				$temp = array();
                \oci_fetch_all($this->_stmt2, $temp, 0, -1, \OCI_FETCHSTATEMENT_BY_ROW + \OCI_ASSOC);		
				$rst = array_replace_recursive($rst, $temp);				
                break;
